#!/bin/bash

echo "Stopping the server..."
pkill gunicorn
sudo service nginx stop

echo "Starting the server..."
cd /home/vagrant/server
sudo service nginx start
gunicorn "app:app" -c /home/vagrant/scripts/gunicorn.py.ini
